routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => ''], function () {
    Route::resource('groups', 'GroupController')->middleware('auth');
});

Route::group(['prefix' => ''], function () {
    Route::resource('groups.students', 'StudentController');

    Route::get('/students','StudentController@index')->middleware('auth')->name('students');
    Route::get('/asynch','StudentController@asynch')->name('asynch');
    Route::get('{groupId}/students/{studentId}/', 'AdminController@gate')->name('adminGates');
    Route::get('{groupId}/students/{studentId}/anket', 'StudentController@anket')->name('anket');
    Route::post('storeStudent', 'StudentController@storeStudent')->middleware('auth')->name('storeStudent');
    Route::post('storeStudentPopUp', 'StudentController@storeStudentPopUp')->middleware('auth')->name('storeStudentPopUp');
    Route::post('updateGroup', 'StudentController@updateGroup')->middleware('auth')->name('updateGroup');

    Route::get('/', 'StudentController@home')->name('home');

    Route::post('/students/anket/image','ImageController@upload')->name('image.upload');

    Route::get('/home/rules', 'StudentController@rulesPdf')->name('home.rulesPdf');


});


Route::group(['prefix' => ''], function () {
    Route::resource('groups.students.scores', 'ScoreController');
});

Route::get('/form', function () {
 return view('form');
})->name('form');


Auth::routes();

Route::get('/service/gate', 'AdminController@gate');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

resources/views/asynch.blade.php
@extends('layouts.app')


@section('content')
<br>
<div class="container" id="content">
    <h2>Список групп</h2>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">Группы</li>
    </ol>
@include('scripts.asynch_script')

</div>
@endsection

resources/views/groups.blade.php
@extends('layouts.app')


@section('content')
    <br>
    <div class="container">
        <h2>Список групп</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Группы</li>
        </ol>
        <table class="table table-striped">
            <thead>
            <th>Название группы</th>
            <th>Описание</th>
            <th class="text-center">Успеваемость</th>
            <th class="text-center">Ср. балл <br>Русский язык</th>
            <th class="text-center">Ср. балл <br>Математика</th>
            <th class="text-center">Ср. балл <br>История</th>
            <!-- <th class="text-right">Просмотр</th>
             <th class="text-right">Редактировать</th>-->
            @if (auth()->user() && (auth()->user()->role == 'admin'))
                <th class="text-right">Удалить</th>
            @endif
            </thead>
            <tbody>
            @forelse ($groups as $group)
                <tr>
                    <td class="text-left"> {{$group->title}}</td>
                    <td>{{$group->description}}</td>

                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 4) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 4));
                        }?></td>
                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 1) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 1));
                        }?></td>

                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 2) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 2));
                        }?></td>
                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 3) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 3));
                        }?></td>
                <!--<td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.show', $group)}}"><i class="fa
                     fa-th-list"></i></a>
                    </td>

                <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.edit', $group)}}"><i class="fa
                     fa-edit"></i></a>
                    </td>-->
                    @if (auth()->user() && (auth()->user()->role == 'admin'))
                        <td class="text-right">
                            <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                                  action="{{route('groups.destroy',$group)}}" method="post">
                                <input type="hidden" name="_method" value="delete">
                                {{csrf_field()}}

                                <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                            </form>
                        </td>
                    @endif
                </tr>
            @empty
            @endforelse
            </tbody>
        </table>
        <hr>
        <?php echo $groups->render(); ?>
        @if (auth()->user() && (auth()->user()->role == 'admin'))
            @include('groups.group.create')
        @endif
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')


@section('content')

    @include('home.filter')
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Главная страница</h2>
            </div>
            <div class="col-md-6">

            </div>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                <th>Групп</th>
                <th>Студент</th>
                <th>Дата рождения</th>
                <th class="text-center">Русский язык</th>
                <th class="text-center">Математика</th>
                <th class="text-center">История</th>
                <th class="text-center">Успеваемость</th>
                @if (auth()->user() && (auth()->user()->role == 'admin'))
                    <th class="text-right">Анкета</th>
                    <th class="text-right">Удалить</th>
                @endif
                </thead>
                <tbody>
                @forelse ($students as $student)
                    <tr>

                        <td class="text-left"> {{$student->group->title}}</td>
                        <td class="text-left"> {{$student->name}}</td>
                        <td class="text-left"> {{$student->birthdayConvert($student->birthday)}}</td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 1) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 1));
                            }?></td>

                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 2) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 2));
                            }?></td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 3) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 3));
                            }?></td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 4) == '0') {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 4));
                            }?></td>

                        @if (auth()->user() && (auth()->user()->role == 'admin'))

                            <td class="text-right">
                                <a class="btn btn-default"
                                   href="{{route('adminGates', [$student->group_id, $student])}}"><i class="fa
                                     fa-edit"></i></a>
                            </td>
                            <td class="text-right">
                                <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                                      action="{{route('groups.students.destroy',[$student->group_id, $student])}}"
                                      method="post">
                                    <input type="hidden" name="_method" value="delete">
                                    {{csrf_field()}}

                                    <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                                </form>
                            </td>
                        @endif
                    </tr>
                @empty
                @endforelse

            </table>
        </div>
        @include('paginate',['paginate'=>$students->appends('home')])

    </div>
@endsection

resources/views/not_allowed.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Ошибка</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        Извините! У вас нет прав доступа. =(
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/paginate.blade.php
<?php

$total=$paginate->total();
$perPage = $paginate->perPage();
$lastPage = ceil($total/$perPage);
$curPage = $paginate->currentPage();
?>
<nav>
    <ul class="pagination">
        <?php $url = $paginate->url(1) ?>
        <li @if($curPage ==1 )class="page-item disabled"@endif>
            <a class="page-link" href="{{ $url }}">
                Previous
            </a>
        </li>
        <?php $p=1 ?>
        @while($p<=$lastPage)
            <?php $url = $paginate->url($p) ?>
            <li  @if($curPage == $p) class="page-item active" @endif>
                <a class="page-link" href="{{ $url }}">
                    {{ $p }}
                        <span class="sr-only">(current)</span>
                </a>
            </li>
            <?php $p=$p+1; ?>
        @endwhile
        <?php $url = $paginate->url($lastPage) ?>
        <li @if($curPage == $lastPage )class="page-item disabled"@endif>
            <a  class="page-link" href="{{ $url }}" >Next
            </a>
        </li>
    </ul>
</nav>

resources/views/students.blade.php
@extends('layouts.app')


@section('content')
    <?php $groups = \App\Models\Group::get();?>
    <br>
    <div class="container">
        <h2>Список студентов</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Главная</a></li>

            <li class="breadcrumb-item active" aria-current="page">Студенты</li>
        </ol>

        <table class="table table-striped">
            <thead>
            <th>Полное имя</th>
            <th>Дата рождения</th>
            <th>Группа</th>
            <th class="text-center">Успеваемость</th>
            <th class="text-center">Ср. балл <br>Русский язык</th>
            <th class="text-center">Ср. балл <br>Математика</th>
            <th class="text-center">Ср. балл <br>История</th>
            @if (auth()->user() && (auth()->user()->role == 'admin'))
                <th class="text-right">Анкета</th>
                <th class="text-right">Удалить</th>
            @endif
            </thead>
        </table>
    </div>
    <div class="container" id="infinite">
        <article class="post">
            <table class="table table-striped">
                <tbody>
                @forelse ($students as $student)
                    <tr>
                        <td class="text-left"> {{$student->name}}</td>
                        <td class="text-left"> {{$student->birthdayConvert($student->birthday)}}</td>
                        <td class="text-left"> {{$student->group->title}}</td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 4) == '0') {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 4));
                            }?></td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 1) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 1));
                            }?></td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 2) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 2));
                            }?></td>
                        <td class="text-center"><?php if ($student->studentMiddleScore($student, 3) == null) {
                                echo '-';
                            } else {
                                echo($student->studentMiddleScore($student, 3));
                            }?></td>
                        @if (auth()->user() && (auth()->user()->role == 'admin'))
                            <td class="text-right">
                                <a class="btn btn-default"
                                   href="{{route('adminGates', [$student->group->id, $student->id])}}"><i class="fa
                                     fa-edit"></i></a>
                            </td>
                            <td class="text-right">
                                <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                                      action="{{route('groups.students.destroy',[$student->group->id,$student->id])}}"
                                      method="post">
                                    <input type="hidden" name="_method" value="delete">
                                    {{csrf_field()}}
                                    <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                                </form>
                            </td>
                        @endif
                    </tr>
                @empty
                @endforelse
                </tbody>
            </table>
        </article>
            <div class="row">
                <div class="col-md-4">
                    <!--                    --><?php // echo $students->render(); ?>
                    <a hidden class="pagination__next" href="students?page=2">Next</a>
                </div>
                {{--@if (auth()->user() && (auth()->user()->role == 'admin'))--}}
                {{--<div class="col-md-8 col-md-offset-4">--}}
                {{--<span class="pull-right">@include('students.edit.form')</span>--}}
                {{--</div>--}}
            </div>
    {{--@include('students.create')--}}

    {{--@endif--}}
    </div>
@endsection