routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => ''], function () {
    Route::resource('groups', 'GroupController')->middleware('auth');
});

Route::group(['prefix' => ''], function () {
    Route::resource('groups.students', 'StudentController');

    Route::get('/students','StudentController@index')->middleware('auth')->name('students');
    Route::get('/asynch','StudentController@asynch')->name('asynch');
    Route::get('{groupId}/students/{studentId}/', 'AdminController@gate')->name('adminGates');
    Route::get('{groupId}/students/{studentId}/anket', 'StudentController@anket')->name('anket');
    Route::post('storeStudent', 'StudentController@storeStudent')->middleware('auth')->name('storeStudent');
    Route::post('storeStudentPopUp', 'StudentController@storeStudentPopUp')->middleware('auth')->name('storeStudentPopUp');
    Route::post('updateGroup', 'StudentController@updateGroup')->middleware('auth')->name('updateGroup');

    Route::get('/', 'StudentController@home')->name('home');

    Route::post('/students/anket/image','ImageController@upload')->name('image.upload');

    Route::get('/home/rules', 'StudentController@rulesPdf')->name('home.rulesPdf');


});


Route::group(['prefix' => ''], function () {
    Route::resource('groups.students.scores', 'ScoreController');
});

Route::get('/form', function () {
 return view('form');
})->name('form');


Auth::routes();

Route::get('/service/gate', 'AdminController@gate');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

app/Models/Score.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Score extends Model
{
    protected $fillable = ['score', 'student_id', 'subject_id'];
    protected $guarded = [];

    public function storeScore($request, $score, $subjectId)
    {

        return array(
            'score' => $request->input($score),
            'subject_id' => $request->input($subjectId),
            'student_id' => $request->input('studentId'),
        );
    }

    public function deleteScore($student, $scoreId)
    {
        $studentId = Score::where('student_id', '=', $student)->first();

        if ($studentId != null) {
            Score::where('id', '=', $scoreId)->first()->delete();
            ++$scoreId;
            Score::where('id', '=', $scoreId)->first()->delete();
            ++$scoreId;
            Score::where('id', '=', $scoreId)->first()->delete();
        }

        return;
    }

    public function student()
    {
        return $this->belongsTo(Student::class);
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Student extends Model
{

    protected $fillable = ['name', 'birthday', 'group_id'];
    protected $guarded = [];

    public function date($request)
    {

        return array(
            'name' => $name = $request->input('name'),
            'birthday' => date('Y-m-d', strtotime($request->input('birthday'))),
            'group_id' => $request->input('group_id'),
            'path' => $request->input('path'),
        );
    }
    function paginateCollection($collection, $perPage, $pageName = 'page', $fragment = null)
    {
        $currentPage = \Illuminate\Pagination\LengthAwarePaginator::resolveCurrentPage($pageName);
        $currentPageItems = $collection->slice(($currentPage - 1) * $perPage, $perPage);
        parse_str(request()->getQueryString(), $query);
        unset($query[$pageName]);
        $paginator = new \Illuminate\Pagination\LengthAwarePaginator(
            $currentPageItems,
           $collection->count(),
            $perPage,
            $currentPage,
            [
                'pageName' => $pageName,
                'path' => \Illuminate\Pagination\LengthAwarePaginator::resolveCurrentPath(),
                'query' => $query,
                'fragment' => $fragment
            ]
        );

        return $paginator;
    }
    public function scopeFilter($query, $filter)
    {

        if ($studentName = array_get($filter, 'studentName')) {

            $query->where('name', $studentName);
        }

        if ($groupTitle = array_get($filter, 'groupTitle')) {

            $query->whereHas('group', function ($q) use ($groupTitle) {
                $q->where('groups.title', $groupTitle);
            });
        }
        if ($russianScore = array_get($filter, 'russianScore')) {

            $query->whereHas('scores', function ($q) use ($russianScore) {
                $q->where('scores.score', $russianScore)->where('scores.subject_id', '1');
            });
        }
        if ($mathScore = array_get($filter, 'mathScore')) {

            $query->whereHas('scores', function ($q) use ($mathScore) {
                $q->where('scores.score', $mathScore)->where('scores.subject_id', '2');
            });
        }
        if ($historyScore = array_get($filter, 'historyScore')) {

            $query->whereHas('scores', function ($q) use ($historyScore) {
                $q->where('scores.score', $historyScore)->where('scores.subject_id', '3');
            });
        }
            return ($query);

    }

    public function birthdayConvert($birthday)
    {
        return $birthday = date('d-m-Y', strtotime($birthday));
    }

    public function studentMiddleScore($student, $subject)
    {
        $middleScoreRussian = collect($student->scores->where('subject_id', '=', '1')->first())->get('score');
        $middleScoreMath = collect($student->scores->where('subject_id', '=', '2')->first())->get('score');
        $middleScoreHistory = collect($student->scores->where('subject_id', '=', '3')->first())->get('score');


        $middleScore = round(($middleScoreRussian + $middleScoreMath + $middleScoreHistory) / 3, 1);

        if ($subject == '1') {

            return $middleScoreRussian;
        } elseif ($subject == '2') {

            return $middleScoreMath;
        } elseif ($subject == '3') {

            return $middleScoreHistory;
        } elseif ($subject == '4') {

            return $middleScore;
        }
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function scores()
    {
        return $this->hasMany(Score::class);
    }
}

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ScoreRequest;
use App\Models\Group;
use App\Models\Score;
use App\Models\Student;
use Illuminate\Http\Request;

class ScoreController extends Controller
{
    public function __construct(Score $score)
    {
        $this->score = $score;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Group $group, Student $student)
    {

        return view('groups.students.scores.index', compact('group', 'student'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ScoreRequest $request)
    {
        $studentId = Score::where('student_id', '=', $request->input('studentId'))->first();

        if ($studentId == null) {
            Score::create($request->merge($this->score->storeScore($request, 'score1', 'subjectId1'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($this->score->storeScore($request, 'score2', 'subjectId2'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($this->score->storeScore($request, 'score3', 'subjectId3'))->only('score',
                'student_id', 'subject_id'));
        }

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Score $score
     * @return \Illuminate\Http\Response
     */
    public function edit($group, $student, $scoreId1)
    {

        return view('groups.students.scores.edit', compact('student', 'group', 'scoreId1'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Score $score
     * @return \Illuminate\Http\Response
     */
    public function update(ScoreRequest $request, $group, $student, $score)
    {
        $studentId = Score::where('student_id', '=', $student)->first();

        if ($studentId != null) {
            $scoreId1 = $score;
            $scoreId2 = $score + 1;
            $scoreId3 = $score + 2;

            Score::where('id', $scoreId1)->update($this->score->storeScore($request, 'score1', 'subjectId1'));
            Score::where('id', $scoreId2)->update($this->score->storeScore($request, 'score2', 'subjectId2'));
            Score::where('id', $scoreId3)->update($this->score->storeScore($request, 'score3', 'subjectId3'));
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Score $score
     * @return \Illuminate\Http\Response
     */
    public function destroy($group, $student, $scoreId)
    {
        $this->score->deleteScore($student, $scoreId);

        return redirect()->back();
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Models\Group;
use App\Models\Score;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;

class StudentController extends Controller
{
    public function __construct(Student $student)
    {
        $this->student = $student;
    }

    public function index()
    {

        return view('students', ['students' => Student::with('group','scores')->paginate(7)]);
    }

    public function asynch()
    {
        return view('asynch');
    }

    public function home(Request $request)
    {

        $students = Student::filter($request)->with('group','scores')->get();

        $perPage=$request->perPage;
        if ($perPage == null)
        {$perPage='10';}

        $groupsFilter = Group::get();
        $studentsFilter = Student::get();

        $s = $this->student->paginateCollection($students, $perPage, 'home');

        return view('home', ['students' => $s, 'filter' => $request,'studentsFilter'=>$studentsFilter,'groupsFilter'=>$groupsFilter]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($groupId)
    {

        return view('groups.students.create')->with('groupId', $groupId);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function anket($group, $student)
    {
        return view('students/anket', compact('group', 'student'));
    }

    public function storeStudent(StudentRequest $request)
    {
        $user = Auth::user();

        if ($user->can('create', Group::class)) {

            $studentId = Student::create($this->student->date($request))->id;
            $score = new Score();
            $request->merge(['studentId' => $studentId]);

            Score::create($request->merge($score->storeScore($request, 'score1', 'subjectId1'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($score->storeScore($request, 'score2', 'subjectId2'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($score->storeScore($request, 'score3', 'subjectId3'))->only('score',
                'student_id', 'subject_id'));

            return redirect()->route('students');
        } else {

            return view('/not_allowed');
        }
    }
    public function storeStudentPopUp(Request $request)
    {
        $user = Auth::user();

        if ($user->can('create', Group::class)) {

            $studentId = Student::create($this->student->date($request))->id;
            $request->merge(['studentId' => $studentId]);

            return redirect()->route('students');
        } else {

            return view('/not_allowed');
        }
    }
    public function rulesPdf()
    {
        $view = view('home.rules_pdf');
        $html = $view->render();
        PDF::SetFont('dejavusans', '', 14, '', true);
        PDF::AddPage();
        PDF::writeHTML($html, true, false, true, false, '');
        PDF::Output('rules.pdf');
    }
    public function store(StudentRequest $request)
    {
        Student::create($this->student->date($request));

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function edit($groupId, $studentId)
    {
        $student = Student::find($studentId);
        $score = Student::with('scores')->where('id', '=', $studentId)->first();

        return view('groups.students.edit')->with(compact('student', 'groupId', 'score'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, Group $group, Student $student)
    {

        Student::where('id', $student->id)->update($student->date($request));

        return redirect()->back();
    }

    public function updateGroup(StudentRequest $request, Group $group, Student $student)
    {

        Student::where('id', $request->student_id)->update(['group_id' => $request->group_id]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group, Student $student)
    {
        $user = Auth::user();

        if ($user->can('delete', Group::class)) {

            $student->delete();

            return redirect()->back();
        } else {

            return view('/not_allowed');
        }
    }
}

resources/views/groups/students/scores/edit.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">

        <h2>Оценки студента</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('groups.students.scores.index',[$group,$student])}}">Оценки
                    студента</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование оценок</li>
        </ol>

    </div>
    <div class="container">
        <h3>Изменение оценок</h3>

        <?php  $studentId = \App\Models\Score::where('student_id', '=', $student)->first();

        if ($studentId != null) {
            $placeScore1 = \App\Models\Score::where('id', '=', $scoreId1)->first()->score;
            $placeScore2 = \App\Models\Score::where('id', '=', $scoreId1 + 1)->first()->score;
            $placeScore3 = \App\Models\Score::where('id', '=', $scoreId1 + 2)->first()->score;
        } else {
            $placeScore1 = "Русский язык";
            $placeScore2 = "Математика";
            $placeScore3 = "История";
        }
        ?>


        <?php $score = collect(['', '', ''])?>
        <?php $subjectId = collect(['', '', ''])?>
        <form class="form-horizontal" action="{{ route('groups.students.scores.update', [$group,$student,$scoreId1])}}"
              method="post">
            <input type="hidden" name="_method" value="put">
            <input type="hidden" name="studentId" value="{{$student}}">
            {{csrf_field()}}
            <table class="table table-striped">
                <thead>
                <th>Русский язык</th>
                <th class="text-center">Математика</th>
                <th class="text-center">История</th>
                <th class="text-center"></th>
                </thead>
                <tbody>

                <tr>
                    <td>
                        <input type="text" class="form-control" name="score1" placeholder="{{$placeScore1}}"
                               value="{{$score[0]}}">
                        <input type="hidden" name="subjectId1" placeholder="" value="{{$subjectId[0]='1'}}">
                    </td>
                    <td>
                        <input type="text" class="form-control" name="score2" placeholder="{{$placeScore2}}"
                               value="{{$score[1]}}">
                        <input type="hidden" name="subjectId2" placeholder="" value="{{$subjectId[1]='2'}}">
                    </td>
                    <td class="text-center">
                        <input type="text" class="form-control" name="score3" placeholder="{{$placeScore3}}"
                               value="{{$score[2]}}">
                        <input type="hidden" name="subjectId3" placeholder="" value="{{$subjectId[2]='3'}}">
                    </td>
                    <td class="text-right">
                        <input class="btn btn-primary" type="submit" value="Изменить оценки">
                    </td>
                </tr>
                </tbody>
            </table>
            <hr/>
        </form>
    </div>
@endsection

resources/views/groups/students/scores/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">

        <h2>Оценки студента</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Оценки студента</li>
        </ol>

        <table class="table table-striped">
            <h1 class="text-center">{{$student->name}}</h1>
            <p class="text-center">{{$student->birthday}}</p>
            <thead>

            <th class=text-center>Русский язык</th>
            <th class="text-center">Математика</th>
            <th class="text-center">История</th>
            <th class="text-center">Средний балл</th>
            <th class="text-right">Изменить оценки</th>
            <th class="text-right">Удалить оценки</th>
            </thead>
            <tbody>

            <?php $sumb = '0';  $scoreId = []; $k = '0' ?>
            @forelse($student->scores as $score)
                <td class="text-center">{{$score->score}}</td>
                <?php $sumb = $sumb + ($score->score)?>
                <?php $scoreId[$k] = ($score->id); ++$k; ?>
            @empty
                <?php $scoreId = [];
                $scoreId[0] = '-'; ?>
                <td class="text-center">-</td>
                <td class="text-center">-</td>
                <td class="text-center">-</td>
            @endforelse

            <td class="text-center"><?php if (count($student->scores) == '0') {
                    echo '-';
                } else {
                    echo round($sumb / count($student->scores), 1);
                }
                ?>
            </td>

            <td class="text-right">

                <a class="btn btn-default"
                   href="{{route('groups.students.scores.edit',[$group->id, $student->id,$scoreId[0]])}}"><i class="fa
                     fa-edit" aria-hidden="true"></i></a>
            </td>
            <td class="text-right">
                <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                      action="{{route('groups.students.scores.destroy',[$group->id, $student->id,$scoreId[0]])}}"
                      method="post">
                    <input type="hidden" name="_method" value="delete">
                    {{csrf_field()}}
                    <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                </form>
            </td>
            </tr>
            </tbody>
        </table>


    </div>
    <div class="container">
        <h3>Добавление оценок</h3>
        <?php $score = collect(['', '', ''])?>
        <?php $subjectId = collect(['', '', ''])?>
        <form class="form-horizontal" action="{{ route('groups.students.scores.store', [$group->id,$student->id]) }}"
              method="post">
            <input type="hidden" name="studentId" value="{{$student->id}}">

            {{csrf_field()}}
            <table class="table table-striped">
                <thead>
                <th>Русский язык</th>
                <th class="text-center">Математика</th>
                <th class="text-center">История</th>
                <th class="text-center"></th>
                </thead>
                <tbody>

                <tr>
                    <td>
                        <input type="text" class="form-control" name="score1" placeholder="Русский язык"
                               value="{{$score[0]}}">
                        <input type="hidden" name="subjectId1" value="{{$subjectId[0]='1'}}">

                    </td>
                    <td>
                        <input type="text" class="form-control" name="score2" placeholder="Математика"
                               value="{{$score[1]}}">
                        <input type="hidden" name="subjectId2" value="{{$subjectId[1]='2'}}">
                    </td>
                    <td class="text-center">
                        <input type="text" class="form-control" name="score3" placeholder="История"
                               value="{{$score[2]}}">
                        <input type="hidden" name="subjectId3" value="{{$subjectId[2]='3'}}">
                    </td>
                    <td class="text-right">
                        <input class="btn btn-primary" type="submit" value="Добавить оценки">

                    </td>
                </tr>
                </tbody>
            </table>
            <hr/>
        </form>
    </div>
@endsection