routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => ''], function () {
    Route::resource('groups', 'GroupController')->middleware('auth');
});

Route::group(['prefix' => ''], function () {
    Route::resource('groups.students', 'StudentController');

    Route::get('/students','StudentController@index')->middleware('auth')->name('students');
    Route::get('/asynch','StudentController@asynch')->name('asynch');
    Route::get('{groupId}/students/{studentId}/', 'AdminController@gate')->name('adminGates');
    Route::get('{groupId}/students/{studentId}/anket', 'StudentController@anket')->name('anket');
    Route::post('storeStudent', 'StudentController@storeStudent')->middleware('auth')->name('storeStudent');
    Route::post('storeStudentPopUp', 'StudentController@storeStudentPopUp')->middleware('auth')->name('storeStudentPopUp');
    Route::post('updateGroup', 'StudentController@updateGroup')->middleware('auth')->name('updateGroup');

    Route::get('/', 'StudentController@home')->name('home');

    Route::post('/students/anket/image','ImageController@upload')->name('image.upload');

    Route::get('/home/rules', 'StudentController@rulesPdf')->name('home.rulesPdf');


});


Route::group(['prefix' => ''], function () {
    Route::resource('groups.students.scores', 'ScoreController');
});

Route::get('/form', function () {
 return view('form');
})->name('form');


Auth::routes();

Route::get('/service/gate', 'AdminController@gate');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Student extends Model
{

    protected $fillable = ['name', 'birthday', 'group_id'];
    protected $guarded = [];

    public function date($request)
    {

        return array(
            'name' => $name = $request->input('name'),
            'birthday' => date('Y-m-d', strtotime($request->input('birthday'))),
            'group_id' => $request->input('group_id'),
            'path' => $request->input('path'),
        );
    }
    function paginateCollection($collection, $perPage, $pageName = 'page', $fragment = null)
    {
        $currentPage = \Illuminate\Pagination\LengthAwarePaginator::resolveCurrentPage($pageName);
        $currentPageItems = $collection->slice(($currentPage - 1) * $perPage, $perPage);
        parse_str(request()->getQueryString(), $query);
        unset($query[$pageName]);
        $paginator = new \Illuminate\Pagination\LengthAwarePaginator(
            $currentPageItems,
           $collection->count(),
            $perPage,
            $currentPage,
            [
                'pageName' => $pageName,
                'path' => \Illuminate\Pagination\LengthAwarePaginator::resolveCurrentPath(),
                'query' => $query,
                'fragment' => $fragment
            ]
        );

        return $paginator;
    }
    public function scopeFilter($query, $filter)
    {

        if ($studentName = array_get($filter, 'studentName')) {

            $query->where('name', $studentName);
        }

        if ($groupTitle = array_get($filter, 'groupTitle')) {

            $query->whereHas('group', function ($q) use ($groupTitle) {
                $q->where('groups.title', $groupTitle);
            });
        }
        if ($russianScore = array_get($filter, 'russianScore')) {

            $query->whereHas('scores', function ($q) use ($russianScore) {
                $q->where('scores.score', $russianScore)->where('scores.subject_id', '1');
            });
        }
        if ($mathScore = array_get($filter, 'mathScore')) {

            $query->whereHas('scores', function ($q) use ($mathScore) {
                $q->where('scores.score', $mathScore)->where('scores.subject_id', '2');
            });
        }
        if ($historyScore = array_get($filter, 'historyScore')) {

            $query->whereHas('scores', function ($q) use ($historyScore) {
                $q->where('scores.score', $historyScore)->where('scores.subject_id', '3');
            });
        }
            return ($query);

    }

    public function birthdayConvert($birthday)
    {
        return $birthday = date('d-m-Y', strtotime($birthday));
    }

    public function studentMiddleScore($student, $subject)
    {
        $middleScoreRussian = collect($student->scores->where('subject_id', '=', '1')->first())->get('score');
        $middleScoreMath = collect($student->scores->where('subject_id', '=', '2')->first())->get('score');
        $middleScoreHistory = collect($student->scores->where('subject_id', '=', '3')->first())->get('score');


        $middleScore = round(($middleScoreRussian + $middleScoreMath + $middleScoreHistory) / 3, 1);

        if ($subject == '1') {

            return $middleScoreRussian;
        } elseif ($subject == '2') {

            return $middleScoreMath;
        } elseif ($subject == '3') {

            return $middleScoreHistory;
        } elseif ($subject == '4') {

            return $middleScore;
        }
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function scores()
    {
        return $this->hasMany(Score::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Models\Group;
use App\Models\Score;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;

class StudentController extends Controller
{
    public function __construct(Student $student)
    {
        $this->student = $student;
    }

    public function index()
    {

        return view('students', ['students' => Student::with('group','scores')->paginate(7)]);
    }

    public function asynch()
    {
        return view('asynch');
    }

    public function home(Request $request)
    {

        $students = Student::filter($request)->with('group','scores')->get();

        $perPage=$request->perPage;
        if ($perPage == null)
        {$perPage='10';}

        $groupsFilter = Group::get();
        $studentsFilter = Student::get();

        $s = $this->student->paginateCollection($students, $perPage, 'home');

        return view('home', ['students' => $s, 'filter' => $request,'studentsFilter'=>$studentsFilter,'groupsFilter'=>$groupsFilter]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($groupId)
    {

        return view('groups.students.create')->with('groupId', $groupId);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function anket($group, $student)
    {
        return view('students/anket', compact('group', 'student'));
    }

    public function storeStudent(StudentRequest $request)
    {
        $user = Auth::user();

        if ($user->can('create', Group::class)) {

            $studentId = Student::create($this->student->date($request))->id;
            $score = new Score();
            $request->merge(['studentId' => $studentId]);

            Score::create($request->merge($score->storeScore($request, 'score1', 'subjectId1'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($score->storeScore($request, 'score2', 'subjectId2'))->only('score',
                'student_id', 'subject_id'));
            Score::create($request->merge($score->storeScore($request, 'score3', 'subjectId3'))->only('score',
                'student_id', 'subject_id'));

            return redirect()->route('students');
        } else {

            return view('/not_allowed');
        }
    }
    public function storeStudentPopUp(Request $request)
    {
        $user = Auth::user();

        if ($user->can('create', Group::class)) {

            $studentId = Student::create($this->student->date($request))->id;
            $request->merge(['studentId' => $studentId]);

            return redirect()->route('students');
        } else {

            return view('/not_allowed');
        }
    }
    public function rulesPdf()
    {
        $view = view('home.rules_pdf');
        $html = $view->render();
        PDF::SetFont('dejavusans', '', 14, '', true);
        PDF::AddPage();
        PDF::writeHTML($html, true, false, true, false, '');
        PDF::Output('rules.pdf');
    }
    public function store(StudentRequest $request)
    {
        Student::create($this->student->date($request));

        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function edit($groupId, $studentId)
    {
        $student = Student::find($studentId);
        $score = Student::with('scores')->where('id', '=', $studentId)->first();

        return view('groups.students.edit')->with(compact('student', 'groupId', 'score'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, Group $group, Student $student)
    {

        Student::where('id', $student->id)->update($student->date($request));

        return redirect()->back();
    }

    public function updateGroup(StudentRequest $request, Group $group, Student $student)
    {

        Student::where('id', $request->student_id)->update(['group_id' => $request->group_id]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group, Student $student)
    {
        $user = Auth::user();

        if ($user->can('delete', Group::class)) {

            $student->delete();

            return redirect()->back();
        } else {

            return view('/not_allowed');
        }
    }
}

resources/views/students/edit/form.blade.php
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Добавить студента
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <?php $score = collect(['', '', ''])?>
    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">
            <form class="form-horizontal" action="{{route('storeStudentPopUp')}}" method="post">
                {{csrf_field()}}
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавление студента</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">


                    <div class="row">
                        <div class="col-md-12">
                            <p class="text">Введите имя студента</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-left"><input type="text" class="form-control" name="name"
                                                        placeholder="Полное имя"></p>
                            <input type="hidden" name="description" value="{{'1'}}">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <p class="text">Введите дату рождения</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-center"><input type="text" class="form-control date placeholder"
                                                          name="birthday"
                                                          placeholder="Дата рождения"></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <p class="text">Введите группу</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <select class="form-control" name="group_id">
                                <option value="">Выберите группу</option>
                                @foreach($groups as $group)

                                    <option value="{{$group->id}}">{{ $group->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <hr>
                    <h6>Ссылки на PDF с правилами</h6>

                    <p><a target="_blank" href="{{ route('home.rulesPdf')}}" class="tooltip-test" title="Tooltip">Правила добавления студента</a>
                        и
                        <a target="_blank" href="{{ route('home.rulesPdf')}}" class="tooltip-test" title="Tooltip">они же</a> только второй ссылкой.</p>
            </div>
            <div class="modal-footer">

                <div class="col-md-6">@include('students.share')</div>
                <div class="col-md-6">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <input class="btn btn-primary" type="submit" value="Добавить"></div>

            </div>

        </form>
        </div>
    </div>
</div>
</div>

resources/views/students/edit/group.blade.php
<form class="form-horizontal" action="{{route('updateGroup',$student)}}" method="post">
    <input type="hidden" name="score1" value="{{$student->group->id}}">
    <input type="hidden" name="score2" value="{{$student->group->id}}">
    <input type="hidden" name="score3" value="{{$student->group->id}}">
    <input type="hidden" name="name" value="{{$student->name}}">
    <input type="hidden" name="birthday" value="{{$student->birthday}}">
    <input type="hidden" name="student_id" value="{{$student->id}}">
    {{csrf_field()}}
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-center">Изменить группу</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            <select class="form-control" name="group_id">
                <option value="">Выберите группу</option>
                @foreach($groups as $group)

                    <option value="{{$group->id}}"{{ $groups }}>{{ $group->title }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-7">
        </div>
        <div class="col-md-4">
            <input class="btn btn-primary" type="submit" value="Изменить">
        </div>
    </div>
</form>

resources/views/students/edit/image.blade.php
<div class="container">
    <form action="{{ route('image.upload') }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="group_id" value="{{$student->group->id}}">
        <input type="hidden" name="name" value="{{$student->name}}">
        <input type="hidden" name="student_id" value="{{$student->id}}">
        <input type="hidden" name="birthday" value="{{$student->birthday}}">
        {{ csrf_field() }}
        @if (isset($student->path))
        <div class="row">
                <div class="col-md-12">
                    <img class="img-fluid" src="{{asset('/storage/' .$student->path)}}" height="150" width="150" alt="">
                </div>
            </div>
        <div class="row">
            <div class="col-md-6">
                <button class="btn btn-primary" type="submit">Изменить</button>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <input type="file" name="image">
                </div>
            </div>
        </div>
@else
            <div class="row">
                <div class="col-md-12">
                    <img class="img-fluid" src="" height="100" width="100" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit">Загрузка</button>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="file" name="image">
                    </div>
                </div>
            </div>
            @endif
    </form>

</div>

resources/views/students/edit/score.blade.php
<?php
if (isset($student->scores[0]->score)) {
    $placeScore1 = $student->scores[0]->score;
    $placeScore2 = $student->scores[1]->score;
    $placeScore3 = $student->scores[2]->score;
} else {
    $placeScore1 = "Русский язык";
    $placeScore2 = "Математика";
    $placeScore3 = "История";
}
?>
@if (isset($student->scores[0]->score))
    <form class="form-horizontal" action="{{route('groups.students.scores.update', [$student->group->id,$student,$student->scores[0]->id])}}"
          method="post">
        <input type="hidden" name="_method" value="put">
        @else
            <form class="form-horizontal"
                  action="{{ route('groups.students.scores.store', [$student->group->id,$student->id]) }}"
                  method="post">
                @endif
                <input type="hidden" name="studentId" value="{{$student->id}}">
                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="text-center">Изменить оценки</h4>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="score1" placeholder="{{$placeScore1}}"
                               value="{{$score[0]}}">
                        <input type="hidden" name="subjectId1" value="{{$subjectId[0]='1'}}">
                        <br>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="score2" placeholder="{{$placeScore2}}"
                               value="{{$score[1]}}">
                        <input type="hidden" name="subjectId2" value="{{$subjectId[1]='2'}}">
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="score3" placeholder="{{$placeScore3}}"
                               value="{{$score[2]}}">
                        <input type="hidden" name="subjectId3" value="{{$subjectId[2]='3'}}">
                        <br>
                    </div>
                    @if (isset($student->scores[0]->score))
                        <div class="col-md-3">
                            <input class="btn btn-primary" type="submit" value="Изменить">
                        </div>
            </form>
            @else
                <div class="col-md-3">
                </div>
                <div class="col-md-3">
                    <input class="btn btn-primary" type="submit" value="Добавить">
                </div>

    </form>
@endif
@if (isset($student->scores[0]->score))
    <div class="col-md-auto">
        <td class="text-right">
            <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                  action="{{route('groups.students.scores.destroy',[$student->group->id, $student->id,$student->scores[0]->id])}}"
                  method="post">
                <input type="hidden" name="_method" value="delete">
                {{csrf_field()}}
                <input class="btn btn-danger" type="submit" value="Удалить">
            </form>
        </td>
    </div>
    @endif
    </div>

resources/views/students/edit/student.blade.php
<form class="form-horizontal" action="{{route('groups.students.update',[$student->group->id, $student])}}" method="post">
    <input type="hidden" name="_method" value="put">
    <input type="hidden" name="group_id" value="{{$student->group->id}}">
    <input type="hidden" name="score1" value="{{$student->group->id}}">
    <input type="hidden" name="score2" value="{{$student->group->id}}">
    <input type="hidden" name="score3" value="{{$student->group->id}}">
    {{csrf_field()}}
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-center">Изменить имя и дату рождения</h4>
            <div class="text-left"><input type="text" class="form-control" name="name"
                                          placeholder="{{$student->name}}">
            </div>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <input type="text" class="form-control date"
                   name="birthday"
                   placeholder={{date('d.m.Y', strtotime($student->birthday))}}>
        </div>
        <div class="col-md-4">
            <input class="btn btn-primary" type="submit" value="Изменить">
        </div>
    </div>
</form>