routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => ''], function () {
    Route::resource('groups', 'GroupController')->middleware('auth');
});

Route::group(['prefix' => ''], function () {
    Route::resource('groups.students', 'StudentController');

    Route::get('/students','StudentController@index')->middleware('auth')->name('students');
    Route::get('/asynch','StudentController@asynch')->name('asynch');
    Route::get('{groupId}/students/{studentId}/', 'AdminController@gate')->name('adminGates');
    Route::get('{groupId}/students/{studentId}/anket', 'StudentController@anket')->name('anket');
    Route::post('storeStudent', 'StudentController@storeStudent')->middleware('auth')->name('storeStudent');
    Route::post('storeStudentPopUp', 'StudentController@storeStudentPopUp')->middleware('auth')->name('storeStudentPopUp');
    Route::post('updateGroup', 'StudentController@updateGroup')->middleware('auth')->name('updateGroup');

    Route::get('/', 'StudentController@home')->name('home');

    Route::post('/students/anket/image','ImageController@upload')->name('image.upload');

    Route::get('/home/rules', 'StudentController@rulesPdf')->name('home.rulesPdf');


});


Route::group(['prefix' => ''], function () {
    Route::resource('groups.students.scores', 'ScoreController');
});

Route::get('/form', function () {
 return view('form');
})->name('form');


Auth::routes();

Route::get('/service/gate', 'AdminController@gate');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Group extends Model
{
    protected $fillable = ['title', 'description'];

    public function indexGroup()
    {
        return ['groups' => Group::with('students.scores')->paginate(6)];
    }

    public function groupMiddleScore($group, $subject)
    {
        $i = 0;
        $middleScoreRussian = [];
        $middleScoreMath = [];
        $middleScoreHistory = [];
        foreach ($group->students as $student) {

            $middleScoreRussian[$i] = $student->scores->where('subject_id', '=', '1')->avg('score');
            $middleScoreMath[$i] = $student->scores->where('subject_id', '=', '2')->avg('score');
            $middleScoreHistory[$i] = $student->scores->where('subject_id', '=', '3')->avg('score');
            ++$i;
        }

        $middleScoreRussian = collect($middleScoreRussian)->reject(function ($value) {
            return $value == null;
        });
        $middleScoreMath = collect($middleScoreMath)->reject(function ($value) {
            return $value == null;
        });
        $middleScoreHistory = collect($middleScoreHistory)->reject(function ($value) {
            return $value == null;
        });

        $middleScoreRussian = round($middleScoreRussian->avg(), 1);
        $middleScoreMath = round($middleScoreMath->avg(), 1);
        $middleScoreHistory = round($middleScoreHistory->avg(), 1);
        $middleScore = round(($middleScoreRussian + $middleScoreMath + $middleScoreHistory) / 3, 1);

        if ($subject == '1') {

            return $middleScoreRussian;
        } elseif ($subject == '2') {

            return $middleScoreMath;
        } elseif ($subject == '3') {

            return $middleScoreHistory;
        } elseif ($subject == '4') {

            return $middleScore;
        }
    }

    public function findFiveScores($group)
    {
        $i = '0';
        $studentName = [];
        foreach ($group->students as $student) {

            $scoreRussian = $student->scores->where('subject_id', '=', '1')->avg('score');
            $scoreMath = $student->scores->where('subject_id', '=', '2')->avg('score');
            $scoreHistory = $student->scores->where('subject_id', '=', '3')->avg('score');
            $middleScore = $scoreRussian + $scoreMath + $scoreHistory;

            if ($middleScore == '15') {

                $studentName[$i] = collect($student)->get('name');
                ++$i;
            }
        }

        return ($studentName);
    }

    public function findGoodScores($group)
    {
        $i = '0';
        $studentName1 = [];
        foreach ($group->students as $student) {

            $scoreRussian = $student->scores->where('subject_id', '=', '1')->avg('score');
            $scoreMath = $student->scores->where('subject_id', '=', '2')->avg('score');
            $scoreHistory = $student->scores->where('subject_id', '=', '3')->avg('score');
            $middleScore = $scoreRussian + $scoreMath + $scoreHistory;

            if ($middleScore < '15' and $middleScore >= '13.5') {
                $studentName = collect($student)->get('name');
                $middleScore = round(($scoreRussian + $scoreMath + $scoreHistory) / 3, 1);
                $studentName1[$i] = collect([$studentName, $scoreRussian, $scoreMath, $scoreHistory, $middleScore]);
                ++$i;
            }
        }

        return $studentName1;
    }

    public function students()
    {
        return $this->hasMany(Student::class);
    }

}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GroupRequest;
use App\Models\Group;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GroupController extends Controller
{
    public function __construct(Group $group)
    {
        $this->group = $group;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('groups', ($this->group->indexGroup()));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();

        if ($user->can('create', Group::class)) {

            return view('groups.create', [
                'groups' => [],
            ]);
        } else {

            return view('/not_allowed');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(GroupRequest $request)
    {

        $user = Auth::user();

        if ($user->can('create', Group::class)) {
            $group = Group::create($request->all());

            return redirect()->route('groups.index', $group);
        } else {

            return view('/not_allowed');
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Group $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        $group = Group::with('students.scores')->where('id', '=', $group->id)->first();
        $students = $group->students()->with('scores')->paginate(6);

        return view('groups.show', compact('group', 'students'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Group $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        $user = Auth::user();

        if ($user->can('edit', Group::class)) {

            return view('groups.edit',
                [
                    'group' => $group,
                ]);
        } else {

            return view('/not_allowed');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Group $group
     * @return \Illuminate\Http\Response
     */
    public function update(GroupRequest $request, Group $group)
    {
        $user = Auth::user();

        if ($user->can('update', Group::class)) {

            $group->update($request->all());

            return redirect()->route('groups.show', $group);
        } else {

            return view('/not_allowed');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group $group
     * @return \Illuminate\Http\Response
     */
    public
    function destroy(
        Group $group
    ) {
        $user = Auth::user();

        if ($user->can('delete', Group::class)) {

            $group->delete();

            return redirect()->route('groups.index');
        } else {

            return view('/not_allowed');
        }
    }
}

resources/views/groups/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Создание группы</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Создать</li>
        </ol>

        <hr/>
        <form class="form-horizontal" action="{{route('groups.store')}}" method="post">
            {{csrf_field()}}
            <label for="">Название группы</label>
            <input type="text" class="form-control" name="title" placeholder="Название группы">
            <label for="">Описание</label>
            <input type="text" class="form-control" name="description" placeholder="Описание">
            <hr/>
            <input class="btn btn-primary" type="submit" value="Добавить">
        </form>

    </div>
@endsection

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Редактирование группы</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>


        </ol>

        <hr/>

        <form class="form-horizontal" action="{{route('groups.update',$group)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{csrf_field()}}


            <label for="">Новое название группы</label>
            <input type="text" class="form-control" name="title" placeholder="{{$group->title}}">
            <label for="">Новое описание</label>
            <input type="text" class="form-control" name="description" placeholder={{$group->description}}>
            <hr/>
            <input class="btn btn-primary" type="submit" value="Изменить">
        </form>

    </div>
@endsection

resources/views/groups/index.blade.php
@extends('layouts.app')


@section('content')
    <br>
    <div class="container">


        <h2>Список групп</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('home')}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Группы</li>
        </ol>


        <table class="table table-striped">
            <thead>
            <th>Название группы</th>
            <th>Описание</th>
            <th class="text-center">Успеваемость</th>
            <th class="text-center">Ср. балл <br>Русский язык</th>
            <th class="text-center">Ср. балл <br>Математика</th>
            <th class="text-center">Ср. балл <br>История</th>
            <!-- <th class="text-right">Просмотр</th>
             <th class="text-right">Редактировать</th>-->
            @if (auth()->user() && (auth()->user()->role == 'admin'))
                <th class="text-right">Удалить</th>
            @endif

            </thead>
            <tbody>
            @forelse ($groups as $group)
                <tr>
                    <td class="text-left"> {{$group->title}}</td>
                    <td>{{$group->description}}</td>

                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 4) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 4));
                        }?></td>
                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 1) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 1));
                        }?></td>

                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 2) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 2));
                        }?></td>
                    <td class="text-center"><?php if ($group->groupMiddleScore($group, 3) == '0') {
                            echo '-';
                        } else {
                            echo($group->groupMiddleScore($group, 3));
                        }?></td>
                 <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.show', $group)}}"><i class="fa
                     fa-th-list"></i></a>
                    </td>

                <!-- <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.edit', $group)}}"><i class="fa
                     fa-edit"></i></a>
                    </td>-->
                    @if (auth()->user() && (auth()->user()->role == 'admin'))
                        <td class="text-right">
                            <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                                  action="{{route('groups.destroy',$group)}}" method="post">
                                <input type="hidden" name="_method" value="delete">
                                {{csrf_field()}}

                                <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                            </form>
                        </td>
                    @endif
                </tr>
            @empty
            @endforelse
            </tbody>
        </table>
        <hr>
        <?php echo $groups->render(); ?>
        @if (auth()->user() && (auth()->user()->role == 'admin'))
            @include('groups.group.create')
        @endif
    </div>
@endsection

resources/views/groups/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">
        <h2>Список студентов</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Студенты</li>
        </ol>
        <hr>
        <table class="table table">
            <h1 class="text-center">{{$group->title}}</h1>
            <p class="text-center">{{$group->description}}</p>
            <thead>
            <th>ФИО студента</th>
            <th>Дата рождения</th>
            <th class="text-center" background="red">Русский язык</th>
            <th class="text-center">Математsdasdasdsadsadика</th>
            <th class="text-center">История</th>
            <th class="text-center">Средний балл</th>
            <th class="text-center">Оценки</th>
            <th class="text-center">Редактировать</th>
            <th class="text-right">Удалить</th>
            </thead>
            <tbody>
            @forelse($students as $student)
                <?php $sumb = '0'?>
                @forelse($student->scores as $score)
                    <?php $sumb = $sumb + ($score->score)?>
                @empty
                @endforelse

                <?php if (count($student->scores) == '0') {
                    $k = '0';
                } else {
                    $k = round($sumb / count($student->scores), 1);
                }?>
                <!-- Перекрашивание ячеек -->
                <?php if ($k != '0' and $k == '5') {

                    $color = 'five';
                } elseif ('5' > $k and $k > '4.5') {

                    $color = 'four';
                } elseif ($k != '0' and $k < '3') {
                    $color = 'three';
                } else {
                    $color = 'default';
                }?>
                <tr class="{{$color}}">
                    <td>{{$student->name}}</td>
                    <?php $birthday = date('d.m.Y', strtotime($student->birthday));?>
                    <td>{{$birthday}}</td>
                    @forelse($student->scores as $score)
                        <td class="text-center">{{$score->score}}</td>
                    @empty
                        <td class="text-center">-</td>
                        <td class="text-center">-</td>
                        <td class="text-center">-</td>
                    @endforelse
                    <td class="text-center">
                        <?php if (count($student->scores) == '0') {
                            echo '-';
                        } else {
                            echo $k;
                        }?>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-default"
                           href="{{route('groups.students.scores.index',[$group->id,$student->id])}}"><i class="fa
                     fa-edit"></i></a>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-default"
                           href="{{route('groups.students.edit',[$group->id, $student->id])}}"><i class="fa
                     fa-edit" aria-hidden="true"></i></a>
                    </td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true}else{return false}"
                              action="{{route('groups.students.destroy',[$group->id, $student])}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            {{csrf_field()}}
                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><h3 class="text-center">Студентов нет</h3></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            @endforelse
            </tbody>
        </table>
        <hr/>
        <td><a href="{{route('groups.students.create', [$group->id])}}" class="btn btn-primary pull-right">Добавить
                студента</a></td>
        <?php echo $students->render(); ?>
    </div>
@endsection